### ISSUE TITLE
Трехрядные формации

### ISSUE THREAD

**Issue by hippogamesunity** [hippogamesunity/SpellMasters#26]
Появилась идея сделать вместо 2-х рядов в отряде 3 ряда. У этой идея я вижу следующие преимущества:
- более оптимальное размещение отряда при эталонном формате экрана 16:9. Сейчас мне пришлось уменьшить масштаб юнитов до такой степени, чтобы в экран поместилась формация из 7 воинов в ряд (вертикально). Если отряд растянуть вширь экрана, то юнитов можно сделать крупнее.
- больше формаций. С 2-мя рядами у нас всего 7 формаций: 0х7, 1х6, 2х5, 3х4, 4х3, 5х2, 6х1. С 3-мя рядами их будет больше.
- больше возможностей для игровой механики. Например, воины с копьем смогут атаковать 2-й ряд, но не 3-й. А лучники по-прежнему смогут атаковать любой ряд. Или появятся скилы, которые наносят урон в линию (как в горизонтальную, так и в вертикальную).

**Comment by aepavlov** [comment]
Меня терзают все-таки сомнения относительно  воинов стоящих в задних/средних рядах, они-то сами почему могут бить, а их нельзя :-) С точки зрения красоты экрана, наверное три ряда удобнее, правда в середине между враждующими армиями должно оставаться пространство, иначе  все  в кучу будет.

**Comment by hippogamesunity** [comment]
Ну конечно должно быть место, где будут летать стрелы и магия) Насчет воинов в задних рядах - конечно это условность, но то же самое было в Disciples II и никто не возмущался)

**Comment by hippogamesunity** [comment]
Реализовал. И теперь возник вопрос - в каком случае юнит ближнего боя не может атаковать врага?
1) Если перед врагом кто-то стоит (в той же горизонтальной колонке)
2) Если в переднем ряду в принципе кто-то есть (не обязательно в той же горизонтальной колонке)
![image](https://user-images.githubusercontent.com/7318172/28022599-4e7a82a4-6594-11e7-83ae-0a1fb0f4eca2.png)

**Comment by aepavlov** [comment]
Ну мне почему-то кажется, что логичнее в той же горизонтальной колонке. А то последний из могикан получается может всю артиллерию защищать:-) Конечно, тоже не баг, а фича, но не нативно.

**Comment by hippogamesunity** [comment]
Реализовано:
- сетка 3х4 (3 ряда, 4 колонны)
- атаковать юнита в ближнем бою нельзя только в том случае, если перед ним непосредственно кто-то стоит.
