### ISSUE TITLE
Индивидуальная прокачка юнитов

### ISSUE THREAD

**Issue by hippogamesunity** [hippogamesunity/SpellMasters#31]
Появилась прикольная идея - при повышении уровня юнита (но не смене профессии) не повышать все параметры юнита, а дать возможность игроку увеличить что-то одно, например атаку, жизнь или мощь скилов. Таким образом игрок сможет создать уникальный отряд, не похожий на другие, и при этом заточенный под статы героя и выбранную тактику боя. Ну и вроде бы не сильно затратно будет сделать.

**Comment by hippogamesunity** [comment]
Развивая эту идею, предлагаю добавить в игру разноцветные кристаллы душ, необходимые для повышения уровня юнита. И игрок сможет сам выбрать, какой кристалл использовать. Кристаллы, добавленные к юниту, сохранятся после смены профессии.

Самые распространенные кристаллы:
- Красный кристалл увеличит здоровье или атаку (на выбор)
- Желтый - увеличит физ. защиту или усилит физические скилы
- Синий - увеличит ману или усилит магические заклинания

Более редкие кристаллы:
- Фиолетовый - увеличит защиту от магии
- Зеленый - увеличит скорость или уклонение
- Оранжевый - увеличит криты

**Comment by hippogamesunity** [comment]
![image](https://user-images.githubusercontent.com/7318172/28067765-47f4c07c-664b-11e7-9852-5eec1647f9d3.png)
https://www.assetstore.unity3d.com/en/#!/content/89910

**Comment by aepavlov** [comment]
А у нас опыт юниты получают ведь по результатам битвы одинаковый? Или это от чего-то зависит. Просто даже не знаю, это надо будет все хранить. Сделать-то можно. 
Допускаю странные вариации - когда будут там лучники-танки или воины-маги :-D 
Вариант с кристаллами все равно получается делает улучшения юнитов примерно того же вида, как если бы просто рос уровень. Ну разве что игрок может вкачивать в одних юнитов больше, в других меньше. Но я думаю это вряд ли так уж сильно повлияет на игру. Понятно, что такого прокаченного воина будут сносить первым. Хотя идею стоит обдумать.

**Comment by hippogamesunity** [comment]
Опыт получают не юниты, а отряд. Чем сильнее соперник, тем больше опыта.
"лучники-танки или воины-маги" будут компенсировать то, что игрок не может выбрать отряд. Получить отряд, чтобы все стояли на своих местах, будет очень не просто. А вот с такой прокачкой отряд можно будет немного "затюнить".

**Comment by hippogamesunity** [comment]
Реализовано.

**Comment by hippogamesunity** [comment]
Идея следующая - при повышении уровня в юнита нужно вставить кристалл души. От кристалла зависит улучшение. Кристаллы будут разной редкости. Редкие кристаллы будут попадаться на высоких уровнях. Дополнительно это повысит реиграбельность.   Т.е. если подкопить редкие кристаллы, то можно создать новый отряд и начать прокачку сразу крутыми кристаллами.

**Comment by Ragewortt** [comment]
он будет работать по принципу обычных кристаллов, только сильнее улучшать параметры юнита (или сразу несколько параметров)?

**Comment by hippogamesunity** [comment]
Обычных кристаллов в игре нет, не очень понял вопрос.
Будет что-то вроде такого:
![image](https://user-images.githubusercontent.com/7318172/29921569-c332a614-8e5a-11e7-8ca7-345f3f6d63b6.png)

Т.е. для повышения уровня потребуются: души, опыт и кристалл душ. Для большинства кристаллов можно будет выбрать эффект. У кристаллов будет своя градация: осколок, кристалл, большой кристалл и др.

Список параметров и соответствующих кристаллов следующий:
Здоровье - Красный
Урон - Красный
Защита - Желтый
Усиление скилов - Желтый
Скорость - Зеленый
Уклонение - Зеленый
Криты - Оранжевый
Мана - Синий
Магическая защита - Синий
Усиление магии - Фиолетовый
