### ISSUE TITLE
Cleric Unit

### ISSUE THREAD

**Issue by Ragewortt** [hippogamesunity/SpellMasters#42]
Два варианта мальчик\девочка. Комментируем что, где подправить.
 
![clerics](https://user-images.githubusercontent.com/22120368/28643716-36d66c10-7270-11e7-9a1c-e5cf89c78150.png)

**Comment by hippogamesunity** [comment]
Да, только волосы надо сделать фиолетовыми, а у тебя они голубые)
Замечаю, что пояс во многих доспехах немного скручен, желательно поправить.
И насчет женских персонажей - не будет ли странным, что после смены профессии юнит изменит пол?) Может быть отклонить идею с женскими персонажами по этой причине? С другой стороны, женские персонажи могут повысить лояльность женской аудитории, хотя она и составит ориентировочно 15-20%.

**Comment by Ragewortt** [comment]
Сорян, то-ли монитор у меня подглючитвает, что эти два цвета сливаются, либо сами глаза уже глючат)
Можно ограничиться прической\глазами а торс оставить плоским. Да и выпуклости издалека не так заметны как голова)

**Comment by hippogamesunity** [comment]
Оставляем парня.
