### ISSUE TITLE
Mercenary Unit

### ISSUE THREAD

**Issue by Ragewortt** [hippogamesunity/SpellMasters#46]
![mercenaryunit](https://user-images.githubusercontent.com/22120368/28686957-6cf136b6-7326-11e7-86cd-456a422ae9b3.png)

**Comment by hippogamesunity** [comment]
Ок, но лучше у рогов цвет изменить на кость или металл.

**Comment by Ragewortt** [comment]
Изначально я цвет рогов с кости брал)
![mercenaryhelm 22](https://user-images.githubusercontent.com/22120368/28747543-f4490efa-74ba-11e7-9010-ebc7865b9234.png)![mercenaryhelm 2](https://user-images.githubusercontent.com/22120368/28747544-f4c46d66-74ba-11e7-8cf0-064604ffaa7f.png)

**Comment by hippogamesunity** [comment]
Лучше бы на юните сразу смотреть, но мне кажется второй лучше. А для редактора оставь оба.
