### ISSUE TITLE
Spearman Unit

### ISSUE THREAD

**Issue by Ragewortt** [hippogamesunity/SpellMasters#49]
![spearmanunit](https://user-images.githubusercontent.com/22120368/28691033-e40f6c1e-7334-11e7-8c3a-27d8a8d834fe.png)

**Comment by hippogamesunity** [comment]
Давай попобуем шлем в цвет доспеха?

**Comment by Ragewortt** [comment]
![spearmanhelm 2](https://user-images.githubusercontent.com/22120368/28747529-7a7b0236-74ba-11e7-9abc-c7b57129c155.png)

**Comment by hippogamesunity** [comment]
ок
