### ISSUE TITLE
Баг с анимацией выстрела из лука

### ISSUE THREAD

**Issue by Ragewortt** [hippogamesunity/SpellMasters#53]
Во время выстрела из лука пропадает скин эквипа на левой руке, даже если он с рукавом.
![tc5wzgbrnlu](https://user-images.githubusercontent.com/22120368/28728844-a7cbd382-73e3-11e7-8393-5b4bcf620363.jpg)

**Comment by hippogamesunity** [comment]
Исправил в редакторе и Dummy. Потребуется пересоздать юнитов, можно не сейчас, т.к. не критично. И еще прошу багам ставить красную метку вместо task.
